FROM python:3.11-alpine

RUN apk add gcc musl-dev libxslt-dev zlib-dev libxml2-dev && \
    pip install parsedmarc && \
    apk del gcc musl-dev libxslt-dev zlib-dev libxml2-dev

CMD ["parsedmarc", "-c", "/etc/parsedmarc/parsedmarc.ini", "--verbose"]
